/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

import type { Enum, Option } from "./common";

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

export type ContractIdInput = { value: string };

export type ContractIdOutput = { value: string };

export type EventInput = {
  uniqueId: BigNumberish;
  owner: IdentityInput;
  name: string;
  price: BigNumberish;
  capacity: BigNumberish;
  numOfRSVPs: BigNumberish;
};

export type EventOutput = {
  uniqueId: BN;
  owner: IdentityOutput;
  name: string;
  price: BN;
  capacity: BN;
  numOfRSVPs: BN;
};

export type IdentityInput = Enum<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;

export type IdentityOutput = Enum<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;

interface EventPlatformAbiInterface extends Interface {
  functions: {
    create_event: FunctionFragment;
    rsvp: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create_event",
    values: [string, BigNumberish, BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "rsvp",
    values: [BigNumberish]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "create_event",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(functionFragment: "rsvp", data: BytesLike): DecodedValue;
}

export class EventPlatformAbi extends Contract {
  interface: EventPlatformAbiInterface;
  functions: {
    create_event: InvokeFunction<
      [
        eventName: string,
        eventPrice: BigNumberish,
        eventCapacity: BigNumberish
      ],
      EventOutput
    >;

    rsvp: InvokeFunction<[eventId: BigNumberish], EventOutput>;
  };
}
